[dev]
  targetPort = 2999 # 연결할 프로젝트 개발 서버의 포트를 지정합니다.
  port = 3000 # 출력할 Netlify 서버의 포트를 지정합니다.


[[edge_functions]]
  path = '/workspaces/*'
  function = 'workspaces' #edge-function에 있는 파일임!!
[[redirects]]
  from = '/*'
  to = '/index.html '
  status = 200
  #force = true


# [[redirects]]
#   from = '/workspaces/*'
#   to = '/.netlify/functions/render'
#   status = 200


